# Generated by Django 5.2.4 on 2025-07-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('last_accessed', models.DateField()),
                ('notes', models.TextField()),
            ],
        ),
    ]
