# Generated by Django 5.2.4 on 2025-07-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='color',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marker',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='marker',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='marker',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
