# Generated by Django 5.2.4 on 2025-07-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_marker_color_marker_latitude_marker_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='notes',
            field=models.TextField(),
        ),
    ]
