# Generated by Django 5.2.4 on 2025-07-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_marker_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
