# Generated by Django 5.2.4 on 2025-07-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_marker_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='address',
            field=models.CharField(max_length=1000),
        ),
    ]
