# Generated by Django 5.2.4 on 2025-07-22 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_client_job_delete_marker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
