# Generated by Django 5.2.4 on 2025-08-02 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_job_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
    ]
